/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.desktop.estol.skeleton.windows;

import org.desktop.estol.skeleton.system.windowloader.LoadWindow;

/**
 *
 * @author estol
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        Licence.setText(GPL2LICENSE + APACHELICENSE);
        Licence.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Licence = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remote Executor - Client");

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Version 0.0.1 Proof of Concept");

        Licence.setEditable(false);
        Licence.setColumns(20);
        Licence.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        Licence.setRows(5);
        jScrollPane1.setViewportView(Licence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void dispose() {
        LoadWindow.LoadWindow.Destroyed(this);
        super.dispose();
    }
    
    private static final String GPL2LICENSE = "Remote Executor Client " +
                                              "Copyright (C) 2014  Péter Szabó, estol, pwyvern@gmail.com\n" +
                                              "\n" +
                                              "This program is free software; you can redistribute it and/or\n" +
                                              "modify it under the terms of the GNU General Public License\n" +
                                              "as published by the Free Software Foundation; either version 2\n" +
                                              "of the License, or (at your option) any later version.\n" +
                                              "\n" +
                                              "This program is distributed in the hope that it will be useful,\n" +
                                              "but WITHOUT ANY WARRANTY; without even the implied warranty of\n" +
                                              "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" +
                                              "GNU General Public License for more details.\n" +
                                              "\n" +
                                              "You should have received a copy of the GNU General Public License\n" +
                                              "along with this program; if not, write to the Free Software\n" +
                                              "Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.";
    
    private static final String APACHELICENSE = "\n\n\nPARTS OF THIS PROGRAM'S CODEBASE ARE BASED ON THE APACHE COMMONS LIBRARY.\n" +
                                                "AVAILABLE UNDER THE APACHE 2.0 LICENSE.\nhttps://www.apache.org/licenses/LICENSE-2.0.html";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Licence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
