package org.desktop.estol.skeleton.windows;

/**
 *
 * @author estol
 */
import org.desktop.estol.skeleton.commons.SelectionListener;
import org.desktop.estol.skeleton.debug.DebugUtilities;
import org.desktop.estol.skeleton.system.windowloader.LoadWindow;
import org.desktop.estol.skeleton.system.windowloader.LoadWindow;

public class DebugWindow extends javax.swing.JFrame
{

    /**
     * Creates new form DebugWindow
     */
    public DebugWindow() {
        initComponents();
        //setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) /2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PeakLabel = new javax.swing.JLabel();
        UsedLabel = new javax.swing.JLabel();
        MaxLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        FreeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CurrentThreadCount = new javax.swing.JLabel();
        PeakThreadCount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DebugPane = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LabelForMouseX = new javax.swing.JLabel();
        LabelForMouseY = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OptionsMenu = new javax.swing.JMenu();
        MemoryMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        KilobyteUnitOption = new javax.swing.JRadioButtonMenuItem();
        MegabyteUnitOption = new javax.swing.JRadioButtonMenuItem();
        GigabyteUnitOption = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SevenhundredFiftyMS = new javax.swing.JMenuItem();
        ThousandNFivehundredMS = new javax.swing.JMenuItem();
        ThreethousandMS = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        AlwaysOnTop = new javax.swing.JCheckBoxMenuItem();
        CopyOnSelectionSwitch = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Debug console");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memory information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 0, 12))); // NOI18N

        PeakLabel.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        PeakLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PeakLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        PeakLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        PeakLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        UsedLabel.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        UsedLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UsedLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        UsedLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        UsedLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        MaxLabel.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        MaxLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MaxLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        MaxLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        MaxLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        TotalLabel.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        TotalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TotalLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        TotalLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        TotalLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        FreeLabel.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        FreeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FreeLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        FreeLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        FreeLabel.setPreferredSize(new java.awt.Dimension(90, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PeakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PeakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thread information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 0, 12))); // NOI18N

        CurrentThreadCount.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        CurrentThreadCount.setText(" ");

        PeakThreadCount.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        PeakThreadCount.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PeakThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentThreadCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(CurrentThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeakThreadCount)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Debug Console", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Condensed", 0, 12))); // NOI18N

        DebugPane.setEditable(false);
        DebugPane.setFont(new java.awt.Font("Ubuntu Mono", 0, 12)); // NOI18N
        DebugPane.setMaximumSize(new java.awt.Dimension(6, 18));
        DebugPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DebugPaneMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DebugPaneMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(DebugPane);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Input details"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mouse"));

        LabelForMouseX.setText("jLabel1");

        LabelForMouseY.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelForMouseX, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(LabelForMouseY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(LabelForMouseX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(LabelForMouseY))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        OptionsMenu.setText("Options");
        OptionsMenu.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        MemoryMenu.setText("Memory");
        MemoryMenu.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jMenuItem1.setText("Unit");
        jMenuItem1.setEnabled(false);
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MemoryMenu.add(jMenuItem1);
        MemoryMenu.add(jSeparator1);

        KilobyteUnitOption.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        KilobyteUnitOption.setText("Kilobyte");
        KilobyteUnitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KilobyteUnitOptionActionPerformed(evt);
            }
        });
        MemoryMenu.add(KilobyteUnitOption);

        MegabyteUnitOption.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        MegabyteUnitOption.setSelected(true);
        MegabyteUnitOption.setText("Megabyte");
        MegabyteUnitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MegabyteUnitOptionActionPerformed(evt);
            }
        });
        MemoryMenu.add(MegabyteUnitOption);

        GigabyteUnitOption.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        GigabyteUnitOption.setText("Gigabyte");
        GigabyteUnitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GigabyteUnitOptionActionPerformed(evt);
            }
        });
        MemoryMenu.add(GigabyteUnitOption);
        MemoryMenu.add(jSeparator2);

        jMenuItem2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jMenuItem2.setText("Refresh Interval");
        jMenuItem2.setEnabled(false);
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MemoryMenu.add(jMenuItem2);
        MemoryMenu.add(jSeparator3);

        SevenhundredFiftyMS.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        SevenhundredFiftyMS.setText("750 ms");
        SevenhundredFiftyMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenhundredFiftyMSActionPerformed(evt);
            }
        });
        MemoryMenu.add(SevenhundredFiftyMS);

        ThousandNFivehundredMS.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ThousandNFivehundredMS.setText("1500 ms");
        ThousandNFivehundredMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThousandNFivehundredMSActionPerformed(evt);
            }
        });
        MemoryMenu.add(ThousandNFivehundredMS);

        ThreethousandMS.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ThreethousandMS.setText("3000 ms");
        ThreethousandMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreethousandMSActionPerformed(evt);
            }
        });
        MemoryMenu.add(ThreethousandMS);

        OptionsMenu.add(MemoryMenu);
        OptionsMenu.add(jSeparator4);

        AlwaysOnTop.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        AlwaysOnTop.setText("Always on top");
        AlwaysOnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlwaysOnTopActionPerformed(evt);
            }
        });
        OptionsMenu.add(AlwaysOnTop);

        CopyOnSelectionSwitch.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        CopyOnSelectionSwitch.setSelected(true);
        CopyOnSelectionSwitch.setText("Copy on selection");
        CopyOnSelectionSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyOnSelectionSwitchActionPerformed(evt);
            }
        });
        OptionsMenu.add(CopyOnSelectionSwitch);

        jMenuBar1.add(OptionsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MegabyteUnitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MegabyteUnitOptionActionPerformed
        KilobyteUnitOption.setSelected(false);
        MegabyteUnitOption.setSelected(true);
        GigabyteUnitOption.setSelected(false);
        DebugUtilities.memoryChangeUnit((byte) 1);
    }//GEN-LAST:event_MegabyteUnitOptionActionPerformed

    private void KilobyteUnitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KilobyteUnitOptionActionPerformed
        KilobyteUnitOption.setSelected(true);
        MegabyteUnitOption.setSelected(false);
        GigabyteUnitOption.setSelected(false);
        DebugUtilities.memoryChangeUnit((byte) 0);
    }//GEN-LAST:event_KilobyteUnitOptionActionPerformed

    private void GigabyteUnitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GigabyteUnitOptionActionPerformed
        KilobyteUnitOption.setSelected(false);
        MegabyteUnitOption.setSelected(false);
        GigabyteUnitOption.setSelected(true);
        DebugUtilities.memoryChangeUnit((byte) 2);
    }//GEN-LAST:event_GigabyteUnitOptionActionPerformed

    private void SevenhundredFiftyMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenhundredFiftyMSActionPerformed
        memoryRefreshIntervalEnabler(0);
    }//GEN-LAST:event_SevenhundredFiftyMSActionPerformed

    private void ThousandNFivehundredMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThousandNFivehundredMSActionPerformed
        memoryRefreshIntervalEnabler(1);
    }//GEN-LAST:event_ThousandNFivehundredMSActionPerformed

    private void ThreethousandMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreethousandMSActionPerformed
        memoryRefreshIntervalEnabler(2);
    }//GEN-LAST:event_ThreethousandMSActionPerformed

    private void CopyOnSelectionSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyOnSelectionSwitchActionPerformed
        if (sl.isEnabled()) {
            sl.disable();
        } else {
            sl.enable();
        }
    }//GEN-LAST:event_CopyOnSelectionSwitchActionPerformed

    private void AlwaysOnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlwaysOnTopActionPerformed
        onTop = !onTop;
        this.setAlwaysOnTop(onTop);
    }//GEN-LAST:event_AlwaysOnTopActionPerformed

    private void DebugPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DebugPaneMousePressed
        sl.getMouseState(evt);
    }//GEN-LAST:event_DebugPaneMousePressed

    private void DebugPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DebugPaneMouseReleased
        sl.getMouseState(evt);
    }//GEN-LAST:event_DebugPaneMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DebugWindow().setVisible(true);
            }
        });
    }

    final void memory() {
        DebugUtilities.startMemoryThread(TotalLabel, FreeLabel, MaxLabel, UsedLabel, PeakLabel, (byte)1);
        memoryRefreshIntervalEnabler(1);
    }
    
    final void threads() {
        DebugUtilities.startThreadmonitorThread(CurrentThreadCount, PeakThreadCount);
    }
    
    final void dConsole() {
        DebugUtilities.startDebugConsoleThread(DebugPane);
    }
    
    final void trackMouse()
    {
        DebugUtilities.startLocationWatch(LabelForMouseX, LabelForMouseY);
    }
    
    void memoryRefreshIntervalEnabler(int mode) {
        switch (mode) {
            case 0:
                SevenhundredFiftyMS.setEnabled(false);
                ThousandNFivehundredMS.setEnabled(true);
                ThreethousandMS.setEnabled(true);
                DebugUtilities.changeUpdateInterval(750);
                break;
            case 1:
                SevenhundredFiftyMS.setEnabled(true);
                ThousandNFivehundredMS.setEnabled(false);
                ThreethousandMS.setEnabled(true);
                DebugUtilities.changeUpdateInterval(1500);
                break;
            case 2:
                SevenhundredFiftyMS.setEnabled(true);
                ThousandNFivehundredMS.setEnabled(true);
                ThreethousandMS.setEnabled(false);
                DebugUtilities.changeUpdateInterval(3000);
                break;
            default:
                SevenhundredFiftyMS.setEnabled(true);
                ThousandNFivehundredMS.setEnabled(false);
                ThreethousandMS.setEnabled(true);
                DebugUtilities.changeUpdateInterval(1500);
                break;
        }
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            memory();
            threads();
            dConsole();
            trackMouse();
            sl = new SelectionListener(DebugPane);
            new Thread(sl).start();
        } else {
            DebugUtilities.memoryShutdown();
            DebugUtilities.threadmonitorShutdown();
            DebugUtilities.unsetDebugConsolePane();
            sl.shutdown();
            dispose();
        }
        super.setVisible(b);
    }

    @Override
    public void dispose() {
        DebugUtilities.memoryShutdown();
        DebugUtilities.threadmonitorShutdown();
        DebugUtilities.locationWatchShutdown();
        sl.shutdown();
        LoadWindow.LoadWindow.Destroyed(this);
        super.dispose();
    }
    
    private SelectionListener sl;
    private static boolean onTop;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem AlwaysOnTop;
    private javax.swing.JCheckBoxMenuItem CopyOnSelectionSwitch;
    private javax.swing.JLabel CurrentThreadCount;
    private javax.swing.JTextPane DebugPane;
    private javax.swing.JLabel FreeLabel;
    private javax.swing.JRadioButtonMenuItem GigabyteUnitOption;
    private javax.swing.JRadioButtonMenuItem KilobyteUnitOption;
    private volatile javax.swing.JLabel LabelForMouseX;
    private volatile javax.swing.JLabel LabelForMouseY;
    private javax.swing.JLabel MaxLabel;
    private javax.swing.JRadioButtonMenuItem MegabyteUnitOption;
    private javax.swing.JMenu MemoryMenu;
    private javax.swing.JMenu OptionsMenu;
    private javax.swing.JLabel PeakLabel;
    private javax.swing.JLabel PeakThreadCount;
    private javax.swing.JMenuItem SevenhundredFiftyMS;
    private javax.swing.JMenuItem ThousandNFivehundredMS;
    private javax.swing.JMenuItem ThreethousandMS;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel UsedLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
