/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.desktop.estol.skeleton.windows;

import java.io.File;
import org.desktop.estol.skeleton.commons.audio.WavePlayer;
import org.desktop.estol.skeleton.debug.DebugUtilities;
import org.desktop.estol.skeleton.system.windowloader.LoadWindow;

/**
 *
 * @author estol
 */
public class Preferences extends javax.swing.JFrame {

    /**
     * Creates new form Preferences
     */
    public Preferences()
    {
        initComponents();
        detectSoundFiles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cb_NotificationSounds = new javax.swing.JComboBox();
        bt_PreviewNotificationSound = new javax.swing.JButton();
        bt_SavePreferences = new javax.swing.JButton();
        bt_DiscardChanges = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel2.setText("Notification Sound");

        cb_NotificationSounds.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cb_NotificationSounds.setEditor(null);
        cb_NotificationSounds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NotificationSoundsActionPerformed(evt);
            }
        });

        bt_PreviewNotificationSound.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        bt_PreviewNotificationSound.setText("Play");
        bt_PreviewNotificationSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PreviewNotificationSoundActionPerformed(evt);
            }
        });

        bt_SavePreferences.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        bt_SavePreferences.setText("Save");
        bt_SavePreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SavePreferencesActionPerformed(evt);
            }
        });

        bt_DiscardChanges.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        bt_DiscardChanges.setText("Discard");
        bt_DiscardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DiscardChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_SavePreferences, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(bt_DiscardChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_NotificationSounds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_PreviewNotificationSound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_NotificationSounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_PreviewNotificationSound, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_SavePreferences)
                    .addComponent(bt_DiscardChanges))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_NotificationSoundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NotificationSoundsActionPerformed
        soundPath = "Sounds" + System.getProperty("file.separator") + cb_NotificationSounds.getSelectedItem();
        DebugUtilities.addDebugMessage(soundPath);
    }//GEN-LAST:event_cb_NotificationSoundsActionPerformed

    private void bt_PreviewNotificationSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PreviewNotificationSoundActionPerformed
        soundPath = "Sounds" + System.getProperty("file.separator") + cb_NotificationSounds.getSelectedItem();
        new WavePlayer().playSound(soundPath);
    }//GEN-LAST:event_bt_PreviewNotificationSoundActionPerformed

    private void bt_DiscardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DiscardChangesActionPerformed
        dispose();
    }//GEN-LAST:event_bt_DiscardChangesActionPerformed

    private void bt_SavePreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SavePreferencesActionPerformed
        //settings.addSetting("notificationSoundPath", soundPath);
        //settings.addSetting("dccPath", dccPath);
        //ml.saveSettings(settings);
        //dispose();
    }//GEN-LAST:event_bt_SavePreferencesActionPerformed
   
    @Override
    public void dispose() {
        LoadWindow.LoadWindow.Destroyed(this);
        super.dispose();
    }
    
    private void detectSoundFiles()
    {
        File[] files = new File("Sounds").listFiles();
        for (File file : files)
        {
            if (file.isFile())
            {
                if (file.getName().endsWith(".wav"))
                {
                    cb_NotificationSounds.addItem(file.getName());
                }
            }
        }
    }
    
    private String soundPath;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_DiscardChanges;
    private javax.swing.JButton bt_PreviewNotificationSound;
    private javax.swing.JButton bt_SavePreferences;
    private javax.swing.JComboBox cb_NotificationSounds;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
